[project]
name = "modem-commander"
version = "0.1.0"
description = "Modem configuration automation tool"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "aiohttp>=3.12.13",
    "pyyaml>=6.0.2",
    "telnetlib3>=2.0.4",
]
